### ISSUE TITLE
`USER` statement with numeric value breaks syntax highlighting

### ISSUE THREAD

**Issue by gruhn** [camdencheek/tree-sitter-dockerfile#30] opened 2023-01-11 18:11 UTC
<img width="392" alt="Screenshot 2023-01-11 at 19 10 58" src="https://user-images.githubusercontent.com/26570572/211884863-27a62c34-9201-477d-83ca-0a6b55eee92c.png">

For copy/paste:
```dockerfile
FROM ubuntu

USER root
WORKDIR /home

USER 1000
WORKDIR /home
```

**Comment by camdencheek** [comment] 2023-01-18 18:17
Thanks for the report!

**Comment by LeoniePhiline** [comment] 2023-04-18 16:42
I can still reproduce the issue. 

See https://github.com/helix-editor/helix/issues/6797

**Comment by Quitlox** [comment] 2023-05-01 10:03
I have found a related issue, albeit in a very specific scenario. It seems that the format `USER <capital letters><dash><any>` breaks the formatting:

![image](https://user-images.githubusercontent.com/7038131/235438295-ce7db727-4a9f-4ba9-8c3b-6bc513ddde69.png)

![image](https://user-images.githubusercontent.com/7038131/235438361-dcb5be14-77ae-479c-b484-59c02d1fe8ac.png)

Should I make a separate issue?

**Comment by LeoniePhiline** [comment] 2023-05-01 12:10
The regex at https://github.com/camdencheek/tree-sitter-dockerfile/blob/8ee3a0f7587b2bd8c45c8cb7d28bd414604aec62/grammar.js#L123 excludes capital letters.

**Comment by camdencheek** [comment] 2024-04-19 20:53
Closing since I can no longer reproduce on the latest `main`

**Closed by camdencheek** 2024-04-19 20:53 UTC
