### ISSUE TITLE
EOF is not handled properly and renders the rest of the file wrong

### ISSUE THREAD

**Issue by aanzolaavila** [camdencheek/tree-sitter-dockerfile#46] opened 2024-03-25 18:44 UTC
When using EOF in a RUN statement, rest of the file would be rendered wrong
Example:
![Screenshot from 2024-03-25 13-42-59](https://github.com/camdencheek/tree-sitter-dockerfile/assets/16315577/b49704cb-0eb8-435c-b3ec-55180d21fc9a)

**Comment by pilona** [comment] 2024-04-01 14:33
@aanzolaavila, this is a duplicate of #4. It's not just about `EOF` as a heredoc marker, but all.

**Comment by aanzolaavila** [comment] 2024-04-08 06:40
I see! thank you for pointing that out! :)

**Closed** 2024-04-08 06:41 UTC
